### ISSUE TITLE
disable dropout

### ISSUE THREAD

**Issue by deeplearningmachine** [Russell91/nlpcaffe#12]
Hi Russell,

What is the easiest way to disable the drop out layers in your model? setting the dropout rate to 0.0?

Thanks in advance,

-DLM

**Comment by Russell91** [comment]
Setting the dropout rate to 0.0 would indeed be the same as removing dropout, which should answer your current question.

However, your original question regarding was what to do to run the model at test time. For a model trained with dropout_ratio 0.2, setting the dropout ration to 0.0 at test time would be a very bad idea. Instead, you want to leave the dropout ratio at 0.2 and set the phase of the net to test. This will get rid of any random dropout, but will multiply the neuron values by 0.8, which keeps the expectation of neuron values the same while removing the randomness. In my experience, these details actually make a huge (e.g. several percent) difference in the quality of the model at test time.

**Comment by deeplearningmachine** [comment]
Thanks a lot, Russell! Very valuable answers. Really appreciated! 

As a follow up question, do I need to specify all dropout layers as Train phrase (currently not in your example .protext file) or these are default settings for drop out? In other words, can I simply use net.set_phase_test() for this purpose?

Thanks.

-DLM

**Comment by Russell91** [comment]
You can find this in the Caffe documentation, but yes. All you should need to do is specify that the net run in the test phase.

**Comment by deeplearningmachine** [comment]
Many Thanks!!

**Comment by Russell91** [comment]
Someone corrected me on a detail that I got wrong here and I just want to set the record straight. Caffe actually does not modify the output of the dropout layer at all during the test phase. It copies the input to the output. During training, the dropout layer sets p% of the values to zero, and multiplies all other values by 1/(1-p).

That being said, you are still recommended to use net.phase = 'test' during the test phase rather than setting dropout_ration = 0.0, as there may be other layers checking net.phase as well and it is the semantically correct thing to be doing.

**Comment by deeplearningmachine** [comment]
Thanks a lot, Russell, for your further clarification! Your help is greatly appreciated!
