### ISSUE TITLE
shed some lights on overcoming the sentence length limit?

### ISSUE THREAD

**Issue by deeplearningmachine** [Russell91/nlpcaffe#16]
Hi Russell,

Would you mind shedding some light on how to work around the max sentence length limitation in the CaffeNLP? With this limitation, it seems that it becomes difficult to encode, for example, sentences with varying numbers of words for some other NLP applications? 

Many thanks,

-DLM

**Comment by Russell91** [comment]
A fixed number of layers is unfortunately a hard limitation of this repository. This has of course been fixed with the ApolloCaffe codebase, which allows variable numbers of layers and supports sequence2sequence with sentences that vary in length in the same batch. The disadvantage of that is the current code hasn't been as highly optimized and the syntax (while cleaner than here) does diverge a little from Caffe.

So I guess the answer is that - yes we have overcome this limitation, but we were only able to do it by creating a new repository.

**Comment by deeplearningmachine** [comment]
Thanks a lot, Russell!

**Comment by DogNick** [comment]
I am working on a CRF layer with sequence log probability loss, and i encontered this problem too, i put the sentence along the third dimension of  each blob  ( N * C * sen_length * 1),  I am considering a fixed max length buffer for each n  , in which a sentence is ended by a predefined symbol , since the input blob of the CRF layer is also an output blob of another net (say , CNN) , i don't know how to notify the sentence end in that output blob for that the net output could be any float number and i dare not to just declare a specific vector as a tail symbol though that output blob still remains the beautiful structure with sentence along the third dimension.

One more thing to be taken into consideration is the efficient when most input sentences is much shorter than the max length.

Would you please give some advice about that?  Many Thanks !

**Comment by lidongliang** [comment]
Hi, I'm working with the nlp-caffe to replicate the neuraltalk code, a video description task. And I find I just cannot predict the end token. It seems that it will predict all the words to the max length. Like below:

uturn butts preparation advancing costmetics travelers preparation preparation slcied slcied slcied slcied slcied slcied slcied slcied slcied slcied slcied slcied

Have you ever encountered with this? Could you give me some advices about it? 
Thank you so much~

**Comment by DogNick** [comment]
I am afraid that i v recognized u ,  li dong liang ,  BUPT  hr?

**Comment by Russell91** [comment]
@lidongliang see https://github.com/Russell91/nlpcaffe/issues/20
